In [18]:
import cv2
import glob
import os
import numpy as np
IMG_SIZE=46

In [48]:
path = r'/home/atif/training_by_several_learning_process/number_classify/rgb_2_gray/Image-classification/test_image/'
img_path = glob.glob(path+ '/*.ppm')

for image_number,image in enumerate(img_path):
    print("\nName of loaded image: ",image)
    cv_img = []
    n= cv2.imread(image)
    n = cv2.resize(n,(48,48))
    n = cv2.cvtColor(n, cv2.COLOR_BGR2GRAY)
    n = cv2.normalize(n, None, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_64F)
#     n = cv2.normalize(n,  n, 0, 255, cv2.NORM_MINMAX) #1st n source, 2nd n output
    cv_img.append(n)
    cv_img = np.array(cv_img)
    cv_img=cv_img.reshape(48,48)
    cv_img = np.rollaxis(cv_img,-1)
    print(cv_img)
    
#     cv_img = cv_img.reshape(IMG_SIZE,IMG_SIZE)
#     print(cv_img)
#     print("one time finish")


Name of loaded image:  /home/atif/training_by_several_learning_process/number_classify/rgb_2_gray/Image-classification/test_image/60_speed.ppm
[[0.03703704 0.04444444 0.03703704 ... 0.0962963  0.11851852 0.18518519]
 [0.02222222 0.02222222 0.01481481 ... 0.08148148 0.11111111 0.17777778]
 [0.02222222 0.01481481 0.02222222 ... 0.08148148 0.0962963  0.16296296]
 ...
 [0.22962963 0.22222222 0.22962963 ... 0.17037037 0.14074074 0.17777778]
 [0.20740741 0.20740741 0.20740741 ... 0.20740741 0.16296296 0.15555556]
 [0.2        0.17037037 0.16296296 ... 0.19259259 0.17777778 0.15555556]]

Name of loaded image:  /home/atif/training_by_several_learning_process/number_classify/rgb_2_gray/Image-classification/test_image/50_speed.ppm
[[0.04149378 0.04979253 0.07883817 ... 0.02904564 0.06224066 0.23236515]
 [0.04979253 0.06224066 0.15352697 ... 0.0373444  0.04149378 0.08298755]
 [0.0746888  0.09543568 0.14107884 ... 0.13278008 0.08713693 0.06639004]
 ...
 [0.01244813 0.01244813 0.01244813 ... 0.029